AWSTemplateFormatVersion: 2010-09-09
Description: A Network sample template
Resources:  
  MustafaVPC:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      CidrBlock: 10.0.0.0/26
  MustafaPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: MustafaVPC
      CidrBlock: 10.0.0.0/28
  MustafaSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: new security group
      VpcId:
        Ref: MustafaVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      Tags:
      - Key: Env
        Value: Dev
      - Key: Purpose
        Value: Testing
  MustafaRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: MustafaVPC
  MustafaIGW:
    Type: AWS::EC2::InternetGateway

Outputs:
  PublicSubnet:
    Description: The subnet ID to use for public web servers
    Value:
      Ref: MustafaPublicSubnet
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-SubnetID"
  WebServerSecurityGroup:
    Description: The security group ID to use for public web servers
    Value:
      Ref: MustafaSG
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-SecurityGroupIDs"
